from datasets import load_dataset
import numpy as np

# Load the smaller dataset
dataset = load_dataset("EvoGym/robots-with-policies")

output_file = "evogym_robots_with_policies.txt"

with open(output_file, "w") as f:
    for i, row in enumerate(dataset["train"]):  # all entries are in "train"
        if row["generated_by"] == "Genetic Algorithm":
            continue  # skip anything not generated by cppn_neat

        runid = 1   # keep constant "1" as in your example
        fitness = row["reward"]
        body = np.array(row["body"])

        # Write runid
        f.write(f"{runid}\n")
        # Write fitness
        f.write(f"{fitness}\n")
        # Write body as 5x5 floats
        for line in body:
            f.write(" ".join([f"{x:.6f}" for x in line]) + "\n")
        f.write("\n")  # blank line between entries
